# Building Input Data File

## Extract Execution Time

In [1]:
folder_results_path = "/run/media/jnsll/Seagate Expansion Drive/exps_modflops/results"

In [2]:
import pandas as pd 

def get_site_name_from_site_number(site_number):
    sites = pd.read_csv(
        "/DATA/These/Projects/Thesis_LAP/"
        + "data/study_sites.txt",
        sep=",",
        header=0,
        index_col=0,
    )  # \\s+
    site_name = sites.index._data[site_number]
    return site_name

In [8]:
print(get_site_name_from_site_number(4))

Jullouville

In [9]:
data = pd.DataFrame(columns = ['Site', 'Chronicle', 'Rate', 'H Error'])

In [12]:
def retrieve_H_error(site_number, site_name, rate):
    if rate == 1:
        folder = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0"
        file_name_BV = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_errorsresult_H_BVE.csv"
    else:
        folder = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Approx0_Period" + str(float(rate))
        file_name_BV = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Approx0_Period" + str(float(rate)) + "_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_errorsresult_H_BVE.csv"
        
    result_file = folder_results_path + "/" + site_name + "/" + folder + "/" + file_name_BV
    try:
        df = pd.read_csv(result_file, sep=";")
    except:
        print("no file", site_number, site_name, rate)
        #print("result_file: ", result_file)
        #print("File for site " + site_name + " (number : " + str(site_number) + " & chronicle 0"  + ") does not exist")
        #df = pd.DataFrame()
        return False
    H = df.iloc[0][0]
    #print(H)
    return H

In [56]:
nb_rates = 30
nb_sites = 40
data = pd.DataFrame(columns = ['Site', 'Rate', 'H Error'])
site_numbers = range(1, nb_sites+1)
#site_numbers = range(1,2)
#rates = [1, 2, 7, 15, 21, 30, 45, 50, 60, 75, 90, 100, 125, 150, 182, 200, 250, 300, 330, 365, 550, 640, 730, 1000, 1500, 2000, 2250, 3000, 3182, 3652]
if nb_rates == 9:
    rates = [1, 2, 7, 30, 90, 182, 365, 730, 3652]
else:
    rates = [1, 2, 7, 15, 21, 30, 45, 50, 60, 75, 90, 100, 125, 150, 182, 200, 250, 300, 330, 365, 550, 640, 730, 1000, 1500, 2000, 2250, 3000, 3182, 3652]
for site_number in site_numbers:
    site_name = get_site_name_from_site_number(site_number)
    print("site number: ", site_number)
    data_site = pd.DataFrame(columns = ['Site', 'Rate', 'H Error'])
    for rate in rates:
        H_error = retrieve_H_error(site_number, site_name, rate)
        if H_error is not False:
            data_site.loc[len(data_site.index)] = [site_number, rate, H_error]
    data_site = data_site.dropna()
    #print(len(data_site))
    if len(data_site)==nb_rates:
        data = pd.concat([data, data_site], ignore_index=True)

data.to_csv("data/Data_Complete_Rates_" + str(nb_rates) + "_Sites_HError_wo_Features_BVE.csv", sep=";", index=None)

site number:  1
site number:  2
site number:  3
site number:  4
site number:  5
site number:  6
site number:  7
site number:  8
site number:  9
no file 9 Port-en-Bessin 1
no file 9 Port-en-Bessin 2
no file 9 Port-en-Bessin 15
no file 9 Port-en-Bessin 21
no file 9 Port-en-Bessin 30
no file 9 Port-en-Bessin 45
no file 9 Port-en-Bessin 50
no file 9 Port-en-Bessin 60
no file 9 Port-en-Bessin 75
no file 9 Port-en-Bessin 90
no file 9 Port-en-Bessin 100
no file 9 Port-en-Bessin 125
no file 9 Port-en-Bessin 150
no file 9 Port-en-Bessin 200
no file 9 Port-en-Bessin 250
no file 9 Port-en-Bessin 300
no file 9 Port-en-Bessin 330
no file 9 Port-en-Bessin 550
no file 9 Port-en-Bessin 640
no file 9 Port-en-Bessin 1000
no file 9 Port-en-Bessin 1500
no file 9 Port-en-Bessin 2000
no file 9 Port-en-Bessin 2250
no file 9 Port-en-Bessin 3000
no file 9 Port-en-Bessin 3182
site number:  10
site number:  11
site number:  12
site number:  13
site number:  14
site number:  15
site number:  16
site number:  17
site number:  18
site number:  19
site number:  20
site number:  21
site number:  22
site number:  23
site number:  24
site number:  25
site number:  26
no file 26 Granville 1
no file 26 Granville 2
no file 26 Granville 7
no file 26 Granville 15
no file 26 Granville 21
no file 26 Granville 30
no file 26 Granville 45
no file 26 Granville 50
no file 26 Granville 60
no file 26 Granville 75
no file 26 Granville 90
no file 26 Granville 100
no file 26 Granville 125
no file 26 Granville 150
no file 26 Granville 182
no file 26 Granville 200
no file 26 Granville 250
no file 26 Granville 300
no file 26 Granville 330
no file 26 Granville 365
no file 26 Granville 550
no file 26 Granville 640
no file 26 Granville 730
no file 26 Granville 1000
no file 26 Granville 1500
no file 26 Granville 2000
no file 26 Granville 2250
no file 26 Granville 3000
no file 26 Granville 3182
no file 26 Granville 3652
site number:  27
site number:  28
site number:  29
site number:  30
site number:  31
site number:  32
site number:  33
site number:  34
site number:  35
site number:  36
site number:  37
site number:  38
site number:  39
site number:  40

## Data SubCatch

In [4]:
data = pd.DataFrame(columns = ['Site', 'Rate', 'H Error'])
data

Empty DataFrame
Columns: [Site, Rate, H Error]
Index: []

In [36]:
def retrieve_H_error(site_number, site_name, rate):
    if rate == 1:
        folder = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0"
        file_name_BV = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_errorsresult_H_BVE_SUB.csv"
    else:
        folder = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Approx0_Period" + str(float(rate))
        file_name_BV = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Approx0_Period" + str(float(rate)) + "_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_errorsresult_H_BVE_SUB.csv"
        
    result_file = folder_results_path + "/" + site_name + "/" + folder + "/" + file_name_BV
    try:
        df = pd.read_csv(result_file, sep=";", index_col=None, names=["SubCatch", "H Error"])
    except:
        #if rate==1:
        print("no file", site_number, site_name, rate)
        #print("result_file: ", result_file)
        #print("File for site " + site_name + " (number : " + str(site_number) + " & chronicle 0"  + ") does not exist")
        df = pd.DataFrame()
        return df
    #print(df)
    #H = df.iloc[0][0]
    #print(H)
    return df

In [53]:
nb_rates = 30
nb_sites = 40
data = pd.DataFrame(columns = ['Site', 'Rate', 'H Error'])
site_numbers = range(1, nb_sites+1)
#site_numbers = range(1,5)
#rates = [1, 2, 7, 15, 21, 30, 45, 50, 60, 75, 90, 100, 125, 150, 182, 200, 250, 300, 330, 365, 550, 640, 730, 1000, 1500, 2000, 2250, 3000, 3182, 3652]
if nb_rates == 9:
    rates = [1, 2, 7, 30, 90, 182, 365, 730, 3652]
else:
    rates = [1, 2, 7, 15, 21, 30, 45, 50, 60, 75, 90, 100, 125, 150, 182, 200, 250, 300, 330, 365, 550, 640, 730, 1000, 1500, 2000, 2250, 3000, 3182, 3652]
#rates = [1, 2]
nb_cases = 0
for site_number in site_numbers:
    #size_complete_data = 0
    site_name = get_site_name_from_site_number(site_number)
    print("site number: ", site_number, site_name)
    data_site = pd.DataFrame(columns = ['Site', 'Rate', 'H Error'])
    nb_rate_valid = 0
    for rate in rates:
        #print(rate)
        H_error = retrieve_H_error(site_number, site_name, rate)
        
        H_error["Site"] = [site_number]*len(H_error)
        H_error["Rate"] = [rate]*len(H_error)
        #print(H_error)
        if H_error.empty:
            continue
        nb_subcatch = max(H_error["SubCatch"].tolist())
        #print(nb_subcatch)
        #size_complete_data += len(H_error)
        #print(H_error)
        if H_error is not False:
            nb_rate_valid += 1
            #data_site.loc[len(data_site.index)] = [site_number, rate, H_error]
        data_site = pd.concat([data_site, H_error], ignore_index=True)
    print(nb_rate_valid)
    #print(len(data_site)%nb_rates)
    if (nb_rate_valid == nb_rates):
        data = pd.concat([data, data_site], ignore_index=True)
        nb_cases += nb_subcatch

#data.to_csv("data/Data_Complete_Rates_" + str(nb_rates) + "_Sites_HError_wo_Features_BVE.csv", sep=";", index=None)
data

site number:  1 Breville-Sur-Mer
no file 1 Breville-Sur-Mer 2
no file 1 Breville-Sur-Mer 45
no file 1 Breville-Sur-Mer 50
no file 1 Breville-Sur-Mer 60
no file 1 Breville-Sur-Mer 75
no file 1 Breville-Sur-Mer 100
no file 1 Breville-Sur-Mer 150
no file 1 Breville-Sur-Mer 200
no file 1 Breville-Sur-Mer 250
no file 1 Breville-Sur-Mer 300
no file 1 Breville-Sur-Mer 330
no file 1 Breville-Sur-Mer 550
no file 1 Breville-Sur-Mer 640
no file 1 Breville-Sur-Mer 1000
no file 1 Breville-Sur-Mer 1500
no file 1 Breville-Sur-Mer 3000
no file 1 Breville-Sur-Mer 3182
13
site number:  2 Agon-Coutainville
30
site number:  3 Saint-Germain-Sur-Ay
no file 3 Saint-Germain-Sur-Ay 1
no file 3 Saint-Germain-Sur-Ay 2
no file 3 Saint-Germain-Sur-Ay 7
no file 3 Saint-Germain-Sur-Ay 15
no file 3 Saint-Germain-Sur-Ay 21
no file 3 Saint-Germain-Sur-Ay 30
no file 3 Saint-Germain-Sur-Ay 45
no file 3 Saint-Germain-Sur-Ay 50
no file 3 Saint-Germain-Sur-Ay 60
no file 3 Saint-Germain-Sur-Ay 75
no file 3 Saint-Germain-Sur-Ay 90
no file 3 Saint-Germain-Sur-Ay 100
no file 3 Saint-Germain-Sur-Ay 125
no file 3 Saint-Germain-Sur-Ay 150
no file 3 Saint-Germain-Sur-Ay 182
no file 3 Saint-Germain-Sur-Ay 200
no file 3 Saint-Germain-Sur-Ay 250
no file 3 Saint-Germain-Sur-Ay 300
no file 3 Saint-Germain-Sur-Ay 330
no file 3 Saint-Germain-Sur-Ay 365
no file 3 Saint-Germain-Sur-Ay 550
no file 3 Saint-Germain-Sur-Ay 640
no file 3 Saint-Germain-Sur-Ay 730
no file 3 Saint-Germain-Sur-Ay 1000
no file 3 Saint-Germain-Sur-Ay 1500
no file 3 Saint-Germain-Sur-Ay 2000
no file 3 Saint-Germain-Sur-Ay 2250
no file 3 Saint-Germain-Sur-Ay 3000
no file 3 Saint-Germain-Sur-Ay 3182
no file 3 Saint-Germain-Sur-Ay 3652
0
site number:  4 Jullouville
no file 4 Jullouville 1
no file 4 Jullouville 2
no file 4 Jullouville 7
no file 4 Jullouville 15
no file 4 Jullouville 21
no file 4 Jullouville 30
no file 4 Jullouville 45
no file 4 Jullouville 50
no file 4 Jullouville 60
no file 4 Jullouville 75
no file 4 Jullouville 90
no file 4 Jullouville 100
no file 4 Jullouville 125
no file 4 Jullouville 150
no file 4 Jullouville 182
no file 4 Jullouville 200
no file 4 Jullouville 250
no file 4 Jullouville 300
no file 4 Jullouville 330
no file 4 Jullouville 365
no file 4 Jullouville 550
no file 4 Jullouville 640
no file 4 Jullouville 730
no file 4 Jullouville 1000
no file 4 Jullouville 1500
no file 4 Jullouville 2000
no file 4 Jullouville 2250
no file 4 Jullouville 3000
no file 4 Jullouville 3182
no file 4 Jullouville 3652
0
site number:  5 Etréham
no file 5 Etréham 7
no file 5 Etréham 30
no file 5 Etréham 90
no file 5 Etréham 100
no file 5 Etréham 125
no file 5 Etréham 150
24
site number:  6 Genêts
no file 6 Genêts 50
no file 6 Genêts 730
no file 6 Genêts 3000
27
site number:  7 Saint-Pair-sur-Mer
no file 7 Saint-Pair-sur-Mer 7
no file 7 Saint-Pair-sur-Mer 640
28
site number:  8 Arromanches-les-Bains
no file 8 Arromanches-les-Bains 21
29
site number:  9 Port-en-Bessin
no file 9 Port-en-Bessin 1
no file 9 Port-en-Bessin 2
no file 9 Port-en-Bessin 15
no file 9 Port-en-Bessin 21
no file 9 Port-en-Bessin 30
no file 9 Port-en-Bessin 45
no file 9 Port-en-Bessin 50
no file 9 Port-en-Bessin 60
no file 9 Port-en-Bessin 75
no file 9 Port-en-Bessin 90
no file 9 Port-en-Bessin 100
no file 9 Port-en-Bessin 125
no file 9 Port-en-Bessin 150
no file 9 Port-en-Bessin 200
no file 9 Port-en-Bessin 250
no file 9 Port-en-Bessin 300
no file 9 Port-en-Bessin 330
no file 9 Port-en-Bessin 550
no file 9 Port-en-Bessin 640
no file 9 Port-en-Bessin 1000
no file 9 Port-en-Bessin 1500
no file 9 Port-en-Bessin 2000
no file 9 Port-en-Bessin 2250
no file 9 Port-en-Bessin 3000
no file 9 Port-en-Bessin 3182
5
site number:  10 Courtils
no file 10 Courtils 1
no file 10 Courtils 2
no file 10 Courtils 7
no file 10 Courtils 15
no file 10 Courtils 21
no file 10 Courtils 30
no file 10 Courtils 45
no file 10 Courtils 50
no file 10 Courtils 60
no file 10 Courtils 75
no file 10 Courtils 90
no file 10 Courtils 100
no file 10 Courtils 125
no file 10 Courtils 150
no file 10 Courtils 182
no file 10 Courtils 200
no file 10 Courtils 250
no file 10 Courtils 300
no file 10 Courtils 330
no file 10 Courtils 365
no file 10 Courtils 550
no file 10 Courtils 640
no file 10 Courtils 730
no file 10 Courtils 1000
no file 10 Courtils 1500
no file 10 Courtils 2000
no file 10 Courtils 2250
no file 10 Courtils 3000
no file 10 Courtils 3182
no file 10 Courtils 3652
0
site number:  11 Lessay
no file 11 Lessay 15
no file 11 Lessay 30
no file 11 Lessay 60
no file 11 Lessay 300
no file 11 Lessay 330
no file 11 Lessay 640
24
site number:  12 Doville
no file 12 Doville 1
no file 12 Doville 2
no file 12 Doville 7
no file 12 Doville 15
no file 12 Doville 21
no file 12 Doville 30
no file 12 Doville 45
no file 12 Doville 50
no file 12 Doville 60
no file 12 Doville 75
no file 12 Doville 90
no file 12 Doville 100
no file 12 Doville 125
no file 12 Doville 150
no file 12 Doville 182
no file 12 Doville 200
no file 12 Doville 250
no file 12 Doville 300
no file 12 Doville 330
no file 12 Doville 365
no file 12 Doville 550
no file 12 Doville 640
no file 12 Doville 730
no file 12 Doville 1000
no file 12 Doville 1500
no file 12 Doville 2000
no file 12 Doville 2250
no file 12 Doville 3000
no file 12 Doville 3182
no file 12 Doville 3652
0
site number:  13 Graye-sur-Mer
30
site number:  14 Saint-Potan
no file 14 Saint-Potan 1
no file 14 Saint-Potan 2
no file 14 Saint-Potan 7
no file 14 Saint-Potan 15
no file 14 Saint-Potan 21
no file 14 Saint-Potan 30
no file 14 Saint-Potan 45
no file 14 Saint-Potan 50
no file 14 Saint-Potan 60
no file 14 Saint-Potan 75
no file 14 Saint-Potan 90
no file 14 Saint-Potan 100
no file 14 Saint-Potan 125
no file 14 Saint-Potan 150
no file 14 Saint-Potan 182
no file 14 Saint-Potan 200
no file 14 Saint-Potan 250
no file 14 Saint-Potan 300
no file 14 Saint-Potan 330
no file 14 Saint-Potan 365
no file 14 Saint-Potan 550
no file 14 Saint-Potan 640
no file 14 Saint-Potan 730
no file 14 Saint-Potan 1000
no file 14 Saint-Potan 1500
no file 14 Saint-Potan 2000
no file 14 Saint-Potan 2250
no file 14 Saint-Potan 3000
no file 14 Saint-Potan 3182
no file 14 Saint-Potan 3652
0
site number:  15 Saint-Vaast-la-Hougue
no file 15 Saint-Vaast-la-Hougue 1
no file 15 Saint-Vaast-la-Hougue 2
no file 15 Saint-Vaast-la-Hougue 7
no file 15 Saint-Vaast-la-Hougue 15
no file 15 Saint-Vaast-la-Hougue 21
no file 15 Saint-Vaast-la-Hougue 30
no file 15 Saint-Vaast-la-Hougue 45
no file 15 Saint-Vaast-la-Hougue 50
no file 15 Saint-Vaast-la-Hougue 60
no file 15 Saint-Vaast-la-Hougue 75
no file 15 Saint-Vaast-la-Hougue 90
no file 15 Saint-Vaast-la-Hougue 100
no file 15 Saint-Vaast-la-Hougue 125
no file 15 Saint-Vaast-la-Hougue 150
no file 15 Saint-Vaast-la-Hougue 182
no file 15 Saint-Vaast-la-Hougue 200
no file 15 Saint-Vaast-la-Hougue 250
no file 15 Saint-Vaast-la-Hougue 300
no file 15 Saint-Vaast-la-Hougue 330
no file 15 Saint-Vaast-la-Hougue 365
no file 15 Saint-Vaast-la-Hougue 550
no file 15 Saint-Vaast-la-Hougue 640
no file 15 Saint-Vaast-la-Hougue 730
no file 15 Saint-Vaast-la-Hougue 1000
no file 15 Saint-Vaast-la-Hougue 1500
no file 15 Saint-Vaast-la-Hougue 2000
no file 15 Saint-Vaast-la-Hougue 2250
no file 15 Saint-Vaast-la-Hougue 3000
no file 15 Saint-Vaast-la-Hougue 3182
no file 15 Saint-Vaast-la-Hougue 3652
0
site number:  16 La_Pernelle
no file 16 La_Pernelle 2
no file 16 La_Pernelle 30
no file 16 La_Pernelle 45
no file 16 La_Pernelle 75
no file 16 La_Pernelle 90
no file 16 La_Pernelle 182
no file 16 La_Pernelle 365
no file 16 La_Pernelle 2000
22
site number:  17 Lestre
no file 17 Lestre 1
no file 17 Lestre 2
no file 17 Lestre 7
no file 17 Lestre 15
no file 17 Lestre 21
no file 17 Lestre 30
no file 17 Lestre 45
no file 17 Lestre 50
no file 17 Lestre 60
no file 17 Lestre 75
no file 17 Lestre 90
no file 17 Lestre 100
no file 17 Lestre 125
no file 17 Lestre 150
no file 17 Lestre 182
no file 17 Lestre 200
no file 17 Lestre 250
no file 17 Lestre 300
no file 17 Lestre 330
no file 17 Lestre 365
no file 17 Lestre 550
no file 17 Lestre 640
no file 17 Lestre 730
no file 17 Lestre 1000
no file 17 Lestre 1500
no file 17 Lestre 2000
no file 17 Lestre 2250
no file 17 Lestre 3000
no file 17 Lestre 3182
no file 17 Lestre 3652
0
site number:  18 Banville
30
site number:  19 Isigny-sur-Mer
30
site number:  20 Saint-Malo
no file 20 Saint-Malo 1
no file 20 Saint-Malo 2
no file 20 Saint-Malo 7
no file 20 Saint-Malo 15
no file 20 Saint-Malo 21
no file 20 Saint-Malo 30
no file 20 Saint-Malo 45
no file 20 Saint-Malo 50
no file 20 Saint-Malo 60
no file 20 Saint-Malo 75
no file 20 Saint-Malo 90
no file 20 Saint-Malo 100
no file 20 Saint-Malo 125
no file 20 Saint-Malo 150
no file 20 Saint-Malo 182
no file 20 Saint-Malo 200
no file 20 Saint-Malo 250
no file 20 Saint-Malo 300
no file 20 Saint-Malo 330
no file 20 Saint-Malo 365
no file 20 Saint-Malo 550
no file 20 Saint-Malo 640
no file 20 Saint-Malo 730
no file 20 Saint-Malo 1000
no file 20 Saint-Malo 1500
no file 20 Saint-Malo 2000
no file 20 Saint-Malo 2250
no file 20 Saint-Malo 3000
no file 20 Saint-Malo 3182
no file 20 Saint-Malo 3652
0
site number:  21 Pierreville
no file 21 Pierreville 30
no file 21 Pierreville 150
no file 21 Pierreville 200
no file 21 Pierreville 250
no file 21 Pierreville 640
no file 21 Pierreville 730
24
site number:  22 La_Feuillie
no file 22 La_Feuillie 2
no file 22 La_Feuillie 7
no file 22 La_Feuillie 15
no file 22 La_Feuillie 21
no file 22 La_Feuillie 30
no file 22 La_Feuillie 45
no file 22 La_Feuillie 50
no file 22 La_Feuillie 90
no file 22 La_Feuillie 100
no file 22 La_Feuillie 125
no file 22 La_Feuillie 150
no file 22 La_Feuillie 182
no file 22 La_Feuillie 200
no file 22 La_Feuillie 250
no file 22 La_Feuillie 300
no file 22 La_Feuillie 365
no file 22 La_Feuillie 730
no file 22 La_Feuillie 1000
no file 22 La_Feuillie 2000
no file 22 La_Feuillie 3652
10
site number:  23 Tourlaville
no file 23 Tourlaville 1
no file 23 Tourlaville 2
no file 23 Tourlaville 7
no file 23 Tourlaville 15
no file 23 Tourlaville 21
no file 23 Tourlaville 30
no file 23 Tourlaville 45
no file 23 Tourlaville 50
no file 23 Tourlaville 60
no file 23 Tourlaville 75
no file 23 Tourlaville 90
no file 23 Tourlaville 100
no file 23 Tourlaville 125
no file 23 Tourlaville 150
no file 23 Tourlaville 182
no file 23 Tourlaville 200
no file 23 Tourlaville 250
no file 23 Tourlaville 300
no file 23 Tourlaville 330
no file 23 Tourlaville 365
no file 23 Tourlaville 550
no file 23 Tourlaville 640
no file 23 Tourlaville 730
no file 23 Tourlaville 1000
no file 23 Tourlaville 1500
no file 23 Tourlaville 2000
no file 23 Tourlaville 2250
no file 23 Tourlaville 3000
no file 23 Tourlaville 3182
no file 23 Tourlaville 3652
0
site number:  24 Octeville
no file 24 Octeville 1
no file 24 Octeville 2
no file 24 Octeville 7
no file 24 Octeville 15
no file 24 Octeville 21
no file 24 Octeville 30
no file 24 Octeville 45
no file 24 Octeville 50
no file 24 Octeville 60
no file 24 Octeville 75
no file 24 Octeville 90
no file 24 Octeville 100
no file 24 Octeville 125
no file 24 Octeville 150
no file 24 Octeville 182
no file 24 Octeville 200
no file 24 Octeville 250
no file 24 Octeville 300
no file 24 Octeville 330
no file 24 Octeville 365
no file 24 Octeville 550
no file 24 Octeville 640
no file 24 Octeville 730
no file 24 Octeville 1000
no file 24 Octeville 1500
no file 24 Octeville 2000
no file 24 Octeville 2250
no file 24 Octeville 3000
no file 24 Octeville 3182
no file 24 Octeville 3652
0
site number:  25 Saint-Briac-sur-Mer
no file 25 Saint-Briac-sur-Mer 1
no file 25 Saint-Briac-sur-Mer 2
no file 25 Saint-Briac-sur-Mer 7
no file 25 Saint-Briac-sur-Mer 15
no file 25 Saint-Briac-sur-Mer 21
no file 25 Saint-Briac-sur-Mer 30
no file 25 Saint-Briac-sur-Mer 45
no file 25 Saint-Briac-sur-Mer 50
no file 25 Saint-Briac-sur-Mer 60
no file 25 Saint-Briac-sur-Mer 75
no file 25 Saint-Briac-sur-Mer 90
no file 25 Saint-Briac-sur-Mer 100
no file 25 Saint-Briac-sur-Mer 125
no file 25 Saint-Briac-sur-Mer 150
no file 25 Saint-Briac-sur-Mer 182
no file 25 Saint-Briac-sur-Mer 200
no file 25 Saint-Briac-sur-Mer 250
no file 25 Saint-Briac-sur-Mer 300
no file 25 Saint-Briac-sur-Mer 330
no file 25 Saint-Briac-sur-Mer 365
no file 25 Saint-Briac-sur-Mer 550
no file 25 Saint-Briac-sur-Mer 640
no file 25 Saint-Briac-sur-Mer 730
no file 25 Saint-Briac-sur-Mer 1000
no file 25 Saint-Briac-sur-Mer 1500
no file 25 Saint-Briac-sur-Mer 2000
no file 25 Saint-Briac-sur-Mer 2250
no file 25 Saint-Briac-sur-Mer 3000
no file 25 Saint-Briac-sur-Mer 3182
no file 25 Saint-Briac-sur-Mer 3652
0
site number:  26 Granville
no file 26 Granville 1
no file 26 Granville 2
no file 26 Granville 7
no file 26 Granville 15
no file 26 Granville 21
no file 26 Granville 30
no file 26 Granville 45
no file 26 Granville 50
no file 26 Granville 60
no file 26 Granville 75
no file 26 Granville 90
no file 26 Granville 100
no file 26 Granville 125
no file 26 Granville 150
no file 26 Granville 182
no file 26 Granville 200
no file 26 Granville 250
no file 26 Granville 300
no file 26 Granville 330
no file 26 Granville 365
no file 26 Granville 550
no file 26 Granville 640
no file 26 Granville 730
no file 26 Granville 1000
no file 26 Granville 1500
no file 26 Granville 2000
no file 26 Granville 2250
no file 26 Granville 3000
no file 26 Granville 3182
no file 26 Granville 3652
0
site number:  27 Blainville-sur-Mer
no file 27 Blainville-sur-Mer 7
no file 27 Blainville-sur-Mer 15
no file 27 Blainville-sur-Mer 21
no file 27 Blainville-sur-Mer 30
no file 27 Blainville-sur-Mer 45
no file 27 Blainville-sur-Mer 50
no file 27 Blainville-sur-Mer 60
no file 27 Blainville-sur-Mer 90
no file 27 Blainville-sur-Mer 150
no file 27 Blainville-sur-Mer 182
no file 27 Blainville-sur-Mer 200
no file 27 Blainville-sur-Mer 250
no file 27 Blainville-sur-Mer 300
no file 27 Blainville-sur-Mer 330
no file 27 Blainville-sur-Mer 365
no file 27 Blainville-sur-Mer 550
no file 27 Blainville-sur-Mer 730
no file 27 Blainville-sur-Mer 1000
no file 27 Blainville-sur-Mer 1500
no file 27 Blainville-sur-Mer 2250
no file 27 Blainville-sur-Mer 3000
no file 27 Blainville-sur-Mer 3182
no file 27 Blainville-sur-Mer 3652
7
site number:  28 Hauteville-sur-Mer
no file 28 Hauteville-sur-Mer 1
no file 28 Hauteville-sur-Mer 2
no file 28 Hauteville-sur-Mer 7
no file 28 Hauteville-sur-Mer 15
no file 28 Hauteville-sur-Mer 21
no file 28 Hauteville-sur-Mer 30
no file 28 Hauteville-sur-Mer 45
no file 28 Hauteville-sur-Mer 50
no file 28 Hauteville-sur-Mer 60
no file 28 Hauteville-sur-Mer 75
no file 28 Hauteville-sur-Mer 90
no file 28 Hauteville-sur-Mer 100
no file 28 Hauteville-sur-Mer 125
no file 28 Hauteville-sur-Mer 150
no file 28 Hauteville-sur-Mer 182
no file 28 Hauteville-sur-Mer 200
no file 28 Hauteville-sur-Mer 250
no file 28 Hauteville-sur-Mer 300
no file 28 Hauteville-sur-Mer 330
no file 28 Hauteville-sur-Mer 365
no file 28 Hauteville-sur-Mer 550
no file 28 Hauteville-sur-Mer 640
no file 28 Hauteville-sur-Mer 730
no file 28 Hauteville-sur-Mer 1000
no file 28 Hauteville-sur-Mer 1500
no file 28 Hauteville-sur-Mer 2000
no file 28 Hauteville-sur-Mer 2250
no file 28 Hauteville-sur-Mer 3000
no file 28 Hauteville-sur-Mer 3182
no file 28 Hauteville-sur-Mer 3652
0
site number:  29 Sainte-Marie-du-Mont
no file 29 Sainte-Marie-du-Mont 2
no file 29 Sainte-Marie-du-Mont 30
no file 29 Sainte-Marie-du-Mont 45
no file 29 Sainte-Marie-du-Mont 60
no file 29 Sainte-Marie-du-Mont 100
no file 29 Sainte-Marie-du-Mont 150
no file 29 Sainte-Marie-du-Mont 200
no file 29 Sainte-Marie-du-Mont 250
no file 29 Sainte-Marie-du-Mont 300
no file 29 Sainte-Marie-du-Mont 330
no file 29 Sainte-Marie-du-Mont 640
no file 29 Sainte-Marie-du-Mont 730
no file 29 Sainte-Marie-du-Mont 2250
no file 29 Sainte-Marie-du-Mont 3182
16
site number:  30 Vierville-sur-Mer
no file 30 Vierville-sur-Mer 1
no file 30 Vierville-sur-Mer 2
no file 30 Vierville-sur-Mer 7
no file 30 Vierville-sur-Mer 15
no file 30 Vierville-sur-Mer 21
no file 30 Vierville-sur-Mer 30
no file 30 Vierville-sur-Mer 45
no file 30 Vierville-sur-Mer 50
no file 30 Vierville-sur-Mer 60
no file 30 Vierville-sur-Mer 75
no file 30 Vierville-sur-Mer 90
no file 30 Vierville-sur-Mer 100
no file 30 Vierville-sur-Mer 125
no file 30 Vierville-sur-Mer 150
no file 30 Vierville-sur-Mer 182
no file 30 Vierville-sur-Mer 200
no file 30 Vierville-sur-Mer 250
no file 30 Vierville-sur-Mer 300
no file 30 Vierville-sur-Mer 330
no file 30 Vierville-sur-Mer 365
no file 30 Vierville-sur-Mer 550
no file 30 Vierville-sur-Mer 640
no file 30 Vierville-sur-Mer 730
no file 30 Vierville-sur-Mer 1000
no file 30 Vierville-sur-Mer 1500
no file 30 Vierville-sur-Mer 2000
no file 30 Vierville-sur-Mer 2250
no file 30 Vierville-sur-Mer 3000
no file 30 Vierville-sur-Mer 3182
no file 30 Vierville-sur-Mer 3652
0
site number:  31 Cherrueix
no file 31 Cherrueix 1
no file 31 Cherrueix 2
no file 31 Cherrueix 7
no file 31 Cherrueix 15
no file 31 Cherrueix 21
no file 31 Cherrueix 30
no file 31 Cherrueix 45
no file 31 Cherrueix 50
no file 31 Cherrueix 60
no file 31 Cherrueix 75
no file 31 Cherrueix 90
no file 31 Cherrueix 100
no file 31 Cherrueix 125
no file 31 Cherrueix 150
no file 31 Cherrueix 182
no file 31 Cherrueix 200
no file 31 Cherrueix 250
no file 31 Cherrueix 300
no file 31 Cherrueix 330
no file 31 Cherrueix 365
no file 31 Cherrueix 550
no file 31 Cherrueix 640
no file 31 Cherrueix 730
no file 31 Cherrueix 1000
no file 31 Cherrueix 1500
no file 31 Cherrueix 2000
no file 31 Cherrueix 2250
no file 31 Cherrueix 3000
no file 31 Cherrueix 3182
no file 31 Cherrueix 3652
0
site number:  32 Chef-du-Pont
no file 32 Chef-du-Pont 1
no file 32 Chef-du-Pont 2
no file 32 Chef-du-Pont 7
no file 32 Chef-du-Pont 15
no file 32 Chef-du-Pont 21
no file 32 Chef-du-Pont 30
no file 32 Chef-du-Pont 45
no file 32 Chef-du-Pont 50
no file 32 Chef-du-Pont 60
no file 32 Chef-du-Pont 75
no file 32 Chef-du-Pont 90
no file 32 Chef-du-Pont 100
no file 32 Chef-du-Pont 125
no file 32 Chef-du-Pont 150
no file 32 Chef-du-Pont 182
no file 32 Chef-du-Pont 200
no file 32 Chef-du-Pont 250
no file 32 Chef-du-Pont 300
no file 32 Chef-du-Pont 330
no file 32 Chef-du-Pont 365
no file 32 Chef-du-Pont 550
no file 32 Chef-du-Pont 640
no file 32 Chef-du-Pont 730
no file 32 Chef-du-Pont 1000
no file 32 Chef-du-Pont 1500
no file 32 Chef-du-Pont 2000
no file 32 Chef-du-Pont 2250
no file 32 Chef-du-Pont 3000
no file 32 Chef-du-Pont 3182
no file 32 Chef-du-Pont 3652
0
site number:  33 Saint-Lô
30
site number:  34 Couvains
no file 34 Couvains 1
no file 34 Couvains 2
28
site number:  35 Rocheville
30
site number:  36 Lison
no file 36 Lison 1
no file 36 Lison 2
no file 36 Lison 7
no file 36 Lison 15
no file 36 Lison 21
no file 36 Lison 30
no file 36 Lison 45
no file 36 Lison 50
no file 36 Lison 60
no file 36 Lison 75
no file 36 Lison 90
no file 36 Lison 100
no file 36 Lison 125
no file 36 Lison 150
no file 36 Lison 182
no file 36 Lison 200
no file 36 Lison 250
no file 36 Lison 300
no file 36 Lison 330
no file 36 Lison 365
no file 36 Lison 550
no file 36 Lison 640
no file 36 Lison 730
no file 36 Lison 1000
no file 36 Lison 1500
no file 36 Lison 2000
no file 36 Lison 2250
no file 36 Lison 3000
no file 36 Lison 3182
no file 36 Lison 3652
0
site number:  37 Marigny
30
site number:  38 Carville
30
site number:  39 Percy
30
site number:  40 Saint-Armand
no file 40 Saint-Armand 1
no file 40 Saint-Armand 2
no file 40 Saint-Armand 7
no file 40 Saint-Armand 15
no file 40 Saint-Armand 21
no file 40 Saint-Armand 30
no file 40 Saint-Armand 45
no file 40 Saint-Armand 50
no file 40 Saint-Armand 60
no file 40 Saint-Armand 75
no file 40 Saint-Armand 90
no file 40 Saint-Armand 100
no file 40 Saint-Armand 125
no file 40 Saint-Armand 150
no file 40 Saint-Armand 182
no file 40 Saint-Armand 200
no file 40 Saint-Armand 250
no file 40 Saint-Armand 300
no file 40 Saint-Armand 330
no file 40 Saint-Armand 365
no file 40 Saint-Armand 550
no file 40 Saint-Armand 640
no file 40 Saint-Armand 730
no file 40 Saint-Armand 1000
no file 40 Saint-Armand 1500
no file 40 Saint-Armand 2000
no file 40 Saint-Armand 2250

     Site  Rate   H Error SubCatch
0       2     1       0.0      1.0
1       2     1       0.0      2.0
2       2     1       0.0      3.0
3       2     1       0.0      4.0
4       2     2  0.003549      1.0
...   ...   ...       ...      ...
1675   39  3652  0.269329      5.0
1676   39  3652  0.349389      4.0
1677   39  3652  0.163505      8.0
1678   39  3652  1.024999      9.0
1679   39  3652  0.274814      7.0

[1680 rows x 4 columns]

In [54]:
len(data)

1680

In [40]:
data = data.dropna()

In [41]:
len(data)

564

In [55]:
data.to_csv("data/Input_Data_Complete_Rates_"+str(nb_rates)+"_SUB_Cases_"+ str(nb_cases)+".csv", sep=";", index=False)

In [57]:
data = pd.read_csv("data/Input_Data_Complete_Rates_"+str(nb_rates)+"_SUB_Cases_"+ str(58)+".csv", sep=";", index_col=None)
print(data)
geomorph_features = pd.read_csv("data/" + "Data_Input_Features_Geomorph_CVHV_BVE_SUB.csv", sep=";", index_col=None)
geomorph_features

      Site  Rate   H Error  SubCatch
0        2     1  0.000000       1.0
1        2     1  0.000000       2.0
2        2     1  0.000000       3.0
3        2     1  0.000000       4.0
4        2     2  0.003549       1.0
...    ...   ...       ...       ...
1470    39  3652  0.269329       5.0
1471    39  3652  0.349389       4.0
1472    39  3652  0.163505       8.0
1473    39  3652  1.024999       9.0
1474    39  3652  0.274814       7.0

[1475 rows x 4 columns]

,Site,SubCatch,Slope,Elevation,LC,SAR,Area,CV,HV
0,1,1,1.203898,8.936689,319.676414,1.000254,1648125,167,211
1,1,2,2.601987,35.812946,653.589956,1.000564,3954375,0,223
2,1,3,3.146334,46.627327,666.589392,1.000757,6120000,0,126
3,1,4,0.827364,7.674784,693.148995,1.000167,2480625,393,163
4,1,5,1.790146,18.949850,930.108903,1.000325,4173750,164,253
...,...,...,...,...,...,...,...,...,...
439,40,15,8.875044,224.490265,933.385135,1.006683,4387500,0,12
440,40,16,6.585227,178.075058,700.135624,1.003876,2930625,0,20
441,40,17,5.182087,173.802765,685.592278,1.002990,3661875,0,34
442,40,18,4.617903,196.079285,597.577939,1.002033,5023125,0,68
443,40,19,2.886285,115.072578,1073.758334,1.000678,697500,0,14

In [58]:
nb_cases = 58
input_data = pd.merge(data, geomorph_features, on=["Site", "SubCatch"])
#del input_data["Chronicle"]
input_data.to_csv("data/Input_Data_Complete_Rates_" + str(nb_rates) + "_Features_Geomorph_CVHV_SUB_Cases_"+str(nb_cases)+".csv", sep=";", index=None)
input_data

,Site,Rate,H Error,SubCatch,Slope,Elevation,LC,SAR,Area,CV,HV
0,2,1,0.000000,1.0,2.035973,29.159981,769.298091,1.000434,9635625,328,431
1,2,2,0.003549,1.0,2.035973,29.159981,769.298091,1.000434,9635625,328,431
2,2,7,0.014516,1.0,2.035973,29.159981,769.298091,1.000434,9635625,328,431
3,2,15,0.023846,1.0,2.035973,29.159981,769.298091,1.000434,9635625,328,431
4,2,21,0.028381,1.0,2.035973,29.159981,769.298091,1.000434,9635625,328,431
...,...,...,...,...,...,...,...,...,...,...,...
1440,39,2000,0.000076,7.0,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1441,39,2250,0.246602,7.0,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1442,39,3000,0.000076,7.0,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1443,39,3182,0.281446,7.0,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1444,39,3652,0.274814,7.0,4.720726,195.869247,672.920859,1.001445,1299375,0,5

In [93]:
r30 = pd.read_csv("data/Input_Data_Complete_Rates_30_SUB_Cases_58.csv", sep=";", index_col=None)
r9 = pd.read_csv("data/Input_Data_Complete_Rates_9_SUB_Cases_68.csv", sep=";", index_col=None)
comp = pd.merge(r30, r9, on=["Site", "SubCatch", "Rate", "H Error"])
comp.dropna()
#comp.iloc[(comp["Rate"]==1 & ]

     Site  Rate   H Error  SubCatch
0       2     1  0.000000       1.0
1       2     1  0.000000       2.0
2       2     1  0.000000       3.0
3       2     1  0.000000       4.0
4       2     2  0.003549       1.0
..    ...   ...       ...       ...
436    39  3652  0.269329       5.0
437    39  3652  0.349389       4.0
438    39  3652  0.163505       8.0
439    39  3652  1.024999       9.0
440    39  3652  0.274814       7.0

[441 rows x 4 columns]

In [119]:
comp_rate = comp.loc[(comp["Rate"]==1)]
comp_rate
#comp_rate2 = comp.loc[(comp["Rate"]==2)]
print(len(comp_rate.loc[:,['Site', 'SubCatch']]))
co = comp_rate.loc[:,['Site', 'SubCatch']]
#print(comp_rate2.loc[:,['Site', 'SubCatch']])
print(co)

49
     Site  SubCatch
0       2       1.0
1       2       2.0
2       2       3.0
3       2       4.0
36     13       1.0
37     13       3.0
54     18       4.0
63     19       1.0
64     19       2.0
81     33       3.0
82     33       2.0
83     33       6.0
84     33       7.0
85     33       8.0
86     33       9.0
135    35       2.0
136    35       7.0
137    35       6.0
138    35       5.0
139    35       4.0
140    35       8.0
141    35       9.0
142    35      12.0
143    35      11.0
144    35      13.0
225    37       3.0
226    37       2.0
227    37       4.0
228    37       5.0
229    37       7.0
230    37      12.0
231    37       6.0
232    37       8.0
233    37       9.0
306    38       1.0
307    38       2.0
308    38       9.0
309    38       3.0
310    38       5.0
311    38       6.0
312    38       7.0
313    38       8.0
378    39       2.0
379    39       3.0
380    39       5.0
381    39       4.0
382    39       8.0
383    39       9.0
384    39       7.0

In [112]:
m30 = pd.merge(co, r30, on=["Site", "SubCatch"])
print(m30)
m30.to_csv("data/Input_Data_Complete_Rates_"+str(30)+"_SUB_Comparable.csv", sep=";", index=False)

      Site  SubCatch  Rate   H Error
0        2       1.0     1  0.000000
1        2       1.0     2  0.003549
2        2       1.0     7  0.014516
3        2       1.0    15  0.023846
4        2       1.0    21  0.028381
...    ...       ...   ...       ...
1463    39       7.0  2000  0.000076
1464    39       7.0  2250  0.246602
1465    39       7.0  3000  0.000076
1466    39       7.0  3182  0.281446
1467    39       7.0  3652  0.274814

[1468 rows x 4 columns]

In [114]:
m9 = pd.merge(co, r9, on=["Site", "SubCatch"])
print(m9)
m9.to_csv("data/Input_Data_Complete_Rates_"+str(9)+"_SUB_Comparable.csv", sep=";", index=False)

     Site  SubCatch  Rate   H Error
0       2       1.0     1  0.000000
1       2       1.0     2  0.003549
2       2       1.0     7  0.014516
3       2       1.0    30  0.037876
4       2       1.0    90  0.091119
..    ...       ...   ...       ...
436    39       7.0    90  0.076823
437    39       7.0   182  0.000076
438    39       7.0   365  0.193669
439    39       7.0   730  0.000076
440    39       7.0  3652  0.274814

[441 rows x 4 columns]

In [120]:
#nb_cases = 58
data_c30 = pd.read_csv("data/Input_Data_Complete_Rates_"+str(30)+"_SUB_Comparable.csv", sep=";", index_col=None)
print(geomorph_features)
input_data = pd.merge(data_c30, geomorph_features, on=["Site", "SubCatch"])
#del input_data["Chronicle"]
input_data.to_csv("data/Input_Data_Complete_Rates_" + str(30) + "_Features_Geomorph_CVHV_SUB_Comparable.csv", sep=";", index=None)
input_data

     Site  SubCatch     Slope   Elevation           LC       SAR     Area  \
0       1         1  1.203898    8.936689   319.676414  1.000254  1648125
1       1         2  2.601987   35.812946   653.589956  1.000564  3954375
2       1         3  3.146334   46.627327   666.589392  1.000757  6120000
3       1         4  0.827364    7.674784   693.148995  1.000167  2480625
4       1         5  1.790146   18.949850   930.108903  1.000325  4173750
..    ...       ...       ...         ...          ...       ...      ...
439    40        15  8.875044  224.490265   933.385135  1.006683  4387500
440    40        16  6.585227  178.075058   700.135624  1.003876  2930625
441    40        17  5.182087  173.802765   685.592278  1.002990  3661875
442    40        18  4.617903  196.079285   597.577939  1.002033  5023125
443    40        19  2.886285  115.072578  1073.758334  1.000678   697500

      CV   HV
0    167  211
1      0  223
2      0  126
3    393  163
4    164  253
..   ...  ...
439    0   12
440    0   20
441    0   34
442    0   68
443    0   14

[444 rows x 9 columns]

,Site,SubCatch,Rate,H Error,Slope,Elevation,LC,SAR,Area,CV,HV
0,2,1.0,1,0.000000,2.035973,29.159981,769.298091,1.000434,9635625,328,431
1,2,1.0,2,0.003549,2.035973,29.159981,769.298091,1.000434,9635625,328,431
2,2,1.0,7,0.014516,2.035973,29.159981,769.298091,1.000434,9635625,328,431
3,2,1.0,15,0.023846,2.035973,29.159981,769.298091,1.000434,9635625,328,431
4,2,1.0,21,0.028381,2.035973,29.159981,769.298091,1.000434,9635625,328,431
...,...,...,...,...,...,...,...,...,...,...,...
1404,39,7.0,2000,0.000076,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1405,39,7.0,2250,0.246602,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1406,39,7.0,3000,0.000076,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1407,39,7.0,3182,0.281446,4.720726,195.869247,672.920859,1.001445,1299375,0,5
1408,39,7.0,3652,0.274814,4.720726,195.869247,672.920859,1.001445,1299375,0,5

In [122]:
data_c9 = pd.read_csv("data/Input_Data_Complete_Rates_"+str(9)+"_SUB_Comparable.csv", sep=";", index_col=None)
print(geomorph_features)
input_data = pd.merge(data_c9, geomorph_features, on=["Site", "SubCatch"])
#del input_data["Chronicle"]
input_data.to_csv("data/Input_Data_Complete_Rates_" + str(9) + "_Features_Geomorph_CVHV_SUB_Comparable.csv", sep=";", index=None)
input_data

     Site  SubCatch     Slope   Elevation           LC       SAR     Area  \
0       1         1  1.203898    8.936689   319.676414  1.000254  1648125
1       1         2  2.601987   35.812946   653.589956  1.000564  3954375
2       1         3  3.146334   46.627327   666.589392  1.000757  6120000
3       1         4  0.827364    7.674784   693.148995  1.000167  2480625
4       1         5  1.790146   18.949850   930.108903  1.000325  4173750
..    ...       ...       ...         ...          ...       ...      ...
439    40        15  8.875044  224.490265   933.385135  1.006683  4387500
440    40        16  6.585227  178.075058   700.135624  1.003876  2930625
441    40        17  5.182087  173.802765   685.592278  1.002990  3661875
442    40        18  4.617903  196.079285   597.577939  1.002033  5023125
443    40        19  2.886285  115.072578  1073.758334  1.000678   697500

      CV   HV
0    167  211
1      0  223
2      0  126
3    393  163
4    164  253
..   ...  ...
439    0   12
440    0   20
441    0   34
442    0   68
443    0   14

[444 rows x 9 columns]

,Site,SubCatch,Rate,H Error,Slope,Elevation,LC,SAR,Area,CV,HV
0,2,1.0,1,0.000000,2.035973,29.159981,769.298091,1.000434,9635625,328,431
1,2,1.0,2,0.003549,2.035973,29.159981,769.298091,1.000434,9635625,328,431
2,2,1.0,7,0.014516,2.035973,29.159981,769.298091,1.000434,9635625,328,431
3,2,1.0,30,0.037876,2.035973,29.159981,769.298091,1.000434,9635625,328,431
4,2,1.0,90,0.091119,2.035973,29.159981,769.298091,1.000434,9635625,328,431
...,...,...,...,...,...,...,...,...,...,...,...
418,39,7.0,90,0.076823,4.720726,195.869247,672.920859,1.001445,1299375,0,5
419,39,7.0,182,0.000076,4.720726,195.869247,672.920859,1.001445,1299375,0,5
420,39,7.0,365,0.193669,4.720726,195.869247,672.920859,1.001445,1299375,0,5
421,39,7.0,730,0.000076,4.720726,195.869247,672.920859,1.001445,1299375,0,5
422,39,7.0,3652,0.274814,4.720726,195.869247,672.920859,1.001445,1299375,0,5

In [121]:
1409/30

46.96666666666667

In [123]:
423/9

47.0

In [126]:
243-18

225

In [115]:
#for r in [1, 2, 7, 15, 21, 30, 45, 50, 60, 75, 90, 100, 125, 150, 182, 200, 250, 300, 330, 365, 550, 640, 730, 1000, 1500, 2000, 2250, 3000, 3182, 3652]:
#    print("rate: ",r)
#    print(len(m30.loc[(m30["Rate"]==r)]))

# Data BVE

## Data BVE 9 Rates

In [51]:
H_data = pd.read_csv("data/Data_Complete_Rates_" + str(nb_rates) + "_Sites_HError_wo_Features_BVE.csv", sep=";", index_col=None)
H_data

     Site    Rate   H Error
0     1.0     1.0  0.000000
1     1.0     2.0  0.003879
2     1.0     7.0  0.016209
3     1.0    30.0  0.042531
4     1.0    90.0  0.105401
..    ...     ...       ...
328  40.0    90.0  0.117949
329  40.0   182.0  0.245425
330  40.0   365.0  0.314390
331  40.0   730.0  0.421673
332  40.0  3652.0  0.529611

[333 rows x 3 columns]

In [52]:
geomorph_features = pd.read_csv("data/" + "Features_Geomorph_BVE.csv", sep=";", index_col=None)
geomorph_features

    Site     Slope  Elevation      LC      CW        Area
0    1.0  0.017383    14.0310  1575.0  2.2527  57077000.0
1    2.0  0.002985     8.0214  1725.0  2.2279  16571000.0
2    3.0  0.000574    10.7040  1425.0  2.0877  20256000.0
3    4.0  0.023758    11.2370  1425.0  2.5802   5203100.0
4    5.0  0.013448    19.0300  1500.0  2.2267  69126000.0
5    6.0  0.036538    12.0600  1425.0  2.4961  20902000.0
6    7.0  0.017869    37.1500  1350.0  2.1056  27810000.0
7    8.0  0.021748     6.9778  1650.0  2.0095   5220000.0
8    9.0  0.009400     7.9139  1800.0  2.0684  46513000.0
9   10.0  0.004804    15.4040  1575.0  1.5889  57802000.0
10  11.0  0.005442    13.0990  1650.0  2.9142  32676000.0
11  12.0  0.041692    15.0480  1425.0  2.0142  95816000.0
12  13.0  0.017000     7.6422  1650.0  2.9322  15452000.0
13  14.0  0.018148    40.5890  1425.0  1.7481  52751000.0
14  15.0  0.026241    19.1890  1500.0  3.2359   4303100.0
15  16.0  0.028223    29.4540  1725.0  2.3301  81242000.0
16  17.0  0.009446    30.5390  1575.0  2.4613  61779000.0
17  18.0  0.020719     6.3567  1425.0  2.2444  10912000.0
18  19.0  0.008119     2.4609  1725.0  2.6646  42446000.0
19  20.0  0.015030    11.7430  1575.0  2.6242  36844000.0
20  21.0  0.033795    45.2920  1350.0  2.4379  38571000.0
21  22.0  0.009653    32.2290  1500.0  2.1629  67568000.0
22  23.0  0.073487    13.1200  1575.0  1.5577   3273800.0
23  24.0  0.038199     5.6431  2700.0  4.0400   3735000.0
24  25.0  0.022180    48.5710  1350.0  1.8653  59490000.0
25  26.0  0.020506    33.7780  1425.0  2.3654  31202000.0
26  27.0  0.014051    16.6780  1725.0  2.7998  74036000.0
27  28.0  0.014850    11.1860  1725.0  2.8374  22202000.0
28  29.0  0.005388     3.0773  1650.0  2.1762  52942000.0
29  30.0  0.009400     7.9139  1800.0  2.0684  46513000.0

In [53]:
input_data = pd.merge(H_data, geomorph_features, on=["Site"])
#del input_data["Chronicle"]
input_data.to_csv("data/Input_Data_Complete_Rates_" + str(nb_rates) + "_Features_Geomorph_BVE.csv", sep=";", index=None)
input_data

     Site    Rate   H Error     Slope  Elevation      LC      CW        Area
0     1.0     1.0  0.000000  0.017383    14.0310  1575.0  2.2527  57077000.0
1     1.0     2.0  0.003879  0.017383    14.0310  1575.0  2.2527  57077000.0
2     1.0     7.0  0.016209  0.017383    14.0310  1575.0  2.2527  57077000.0
3     1.0    30.0  0.042531  0.017383    14.0310  1575.0  2.2527  57077000.0
4     1.0    90.0  0.105401  0.017383    14.0310  1575.0  2.2527  57077000.0
..    ...     ...       ...       ...        ...     ...     ...         ...
238  30.0    90.0  0.047023  0.009400     7.9139  1800.0  2.0684  46513000.0
239  30.0   182.0  0.083012  0.009400     7.9139  1800.0  2.0684  46513000.0
240  30.0   365.0  0.094342  0.009400     7.9139  1800.0  2.0684  46513000.0
241  30.0   730.0  0.119479  0.009400     7.9139  1800.0  2.0684  46513000.0
242  30.0  3652.0  0.168162  0.009400     7.9139  1800.0  2.0684  46513000.0

[243 rows x 8 columns]

In [55]:
geomorph_cvhv_sat = pd.read_csv("data/" + "Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index_col=None)
input_data_11 = pd.merge(H_data, geomorph_cvhv_sat, on=["Site"])
input_data_11.to_csv("data/Input_Data_Complete_Rates_" + str(nb_rates) + "_Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index=None)
input_data_11

,Site,Rate,H Error,Slope,Elevation,LC,CW,Area,Coastal Vulnerability,Hydrological Vulnerability,Satured Zone Area,Vulnerability Sum,Vulnerability Rate,Global Area of site (in cells)
0,1.0,1.0,0.000000,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
1,1.0,2.0,0.003879,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
2,1.0,7.0,0.016209,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
3,1.0,30.0,0.042531,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
4,1.0,90.0,0.105401,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,30.0,90.0,0.047023,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
239,30.0,182.0,0.083012,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
240,30.0,365.0,0.094342,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
241,30.0,730.0,0.119479,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
242,30.0,3652.0,0.168162,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816

## Data BVE 30 Rates

### Features Geomorph

In [57]:
H_data = pd.read_csv("data/Data_Complete_Rates_" + str(nb_rates) + "_Sites_HError_wo_Features_BVE.csv", sep=";", index_col=None)
H_data

      Site    Rate   H Error
0      1.0     1.0  0.000000
1      1.0     2.0  0.003879
2      1.0     7.0  0.016209
3      1.0    15.0  0.025983
4      1.0    21.0  0.031977
...    ...     ...       ...
1045  40.0  2000.0  0.507397
1046  40.0  2250.0  0.486234
1047  40.0  3000.0  0.537969
1048  40.0  3182.0  0.538462
1049  40.0  3652.0  0.529611

[1050 rows x 3 columns]

In [61]:
geomorph_features = pd.read_csv("data/" + "Features_Geomorph_BVE.csv", sep=";", index_col=None)
geomorph_features

    Site     Slope  Elevation      LC      CW        Area
0    1.0  0.017383    14.0310  1575.0  2.2527  57077000.0
1    2.0  0.002985     8.0214  1725.0  2.2279  16571000.0
2    3.0  0.000574    10.7040  1425.0  2.0877  20256000.0
3    4.0  0.023758    11.2370  1425.0  2.5802   5203100.0
4    5.0  0.013448    19.0300  1500.0  2.2267  69126000.0
5    6.0  0.036538    12.0600  1425.0  2.4961  20902000.0
6    7.0  0.017869    37.1500  1350.0  2.1056  27810000.0
7    8.0  0.021748     6.9778  1650.0  2.0095   5220000.0
8    9.0  0.009400     7.9139  1800.0  2.0684  46513000.0
9   10.0  0.004804    15.4040  1575.0  1.5889  57802000.0
10  11.0  0.005442    13.0990  1650.0  2.9142  32676000.0
11  12.0  0.041692    15.0480  1425.0  2.0142  95816000.0
12  13.0  0.017000     7.6422  1650.0  2.9322  15452000.0
13  14.0  0.018148    40.5890  1425.0  1.7481  52751000.0
14  15.0  0.026241    19.1890  1500.0  3.2359   4303100.0
15  16.0  0.028223    29.4540  1725.0  2.3301  81242000.0
16  17.0  0.009446    30.5390  1575.0  2.4613  61779000.0
17  18.0  0.020719     6.3567  1425.0  2.2444  10912000.0
18  19.0  0.008119     2.4609  1725.0  2.6646  42446000.0
19  20.0  0.015030    11.7430  1575.0  2.6242  36844000.0
20  21.0  0.033795    45.2920  1350.0  2.4379  38571000.0
21  22.0  0.009653    32.2290  1500.0  2.1629  67568000.0
22  23.0  0.073487    13.1200  1575.0  1.5577   3273800.0
23  24.0  0.038199     5.6431  2700.0  4.0400   3735000.0
24  25.0  0.022180    48.5710  1350.0  1.8653  59490000.0
25  26.0  0.020506    33.7780  1425.0  2.3654  31202000.0
26  27.0  0.014051    16.6780  1725.0  2.7998  74036000.0
27  28.0  0.014850    11.1860  1725.0  2.8374  22202000.0
28  29.0  0.005388     3.0773  1650.0  2.1762  52942000.0
29  30.0  0.009400     7.9139  1800.0  2.0684  46513000.0

In [62]:
input_data = pd.merge(H_data, geomorph_features, on=["Site"])
#del input_data["Chronicle"]
input_data.to_csv("data/Input_Data_Complete_Rates_" + str(nb_rates) + "_Features_Geomorph_BVE.csv", sep=";", index=None)
input_data

     Site    Rate   H Error     Slope  Elevation      LC      CW        Area
0     1.0     1.0  0.000000  0.017383    14.0310  1575.0  2.2527  57077000.0
1     1.0     2.0  0.003879  0.017383    14.0310  1575.0  2.2527  57077000.0
2     1.0     7.0  0.016209  0.017383    14.0310  1575.0  2.2527  57077000.0
3     1.0    15.0  0.025983  0.017383    14.0310  1575.0  2.2527  57077000.0
4     1.0    21.0  0.031977  0.017383    14.0310  1575.0  2.2527  57077000.0
..    ...     ...       ...       ...        ...     ...     ...         ...
745  30.0  2000.0  0.142734  0.009400     7.9139  1800.0  2.0684  46513000.0
746  30.0  2250.0  0.150898  0.009400     7.9139  1800.0  2.0684  46513000.0
747  30.0  3000.0  0.161572  0.009400     7.9139  1800.0  2.0684  46513000.0
748  30.0  3182.0  0.165746  0.009400     7.9139  1800.0  2.0684  46513000.0
749  30.0  3652.0  0.168162  0.009400     7.9139  1800.0  2.0684  46513000.0

[750 rows x 8 columns]

In [54]:
geomorph_cvhv_sat = pd.read_csv("data/" + "Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index_col=None)

In [ ]:
geomorph_cvhv_sat = pd.read_csv("data/" + "Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index_col=None)
input_data_11 = pd.merge(H_data, geomorph_cvhv_sat, on=["Site"])
input_data_11.to_csv("data/Input_Data_Complete_Rates_30_Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index=None)
input_data_11

### Features Geomorph CVHV Saturation

In [43]:
geomorph_cvhv_sat = pd.read_csv("data/" + "Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index_col=None)
geomorph_cvhv_sat

,Site,Slope,Elevation,LC,CW,Area,Coastal Vulnerability,Hydrological Vulnerability,Satured Zone Area,Vulnerability Sum,Vulnerability Rate,Global Area of site (in cells)
0,1.0,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
1,2.0,0.002985,8.0214,1725.0,2.2279,16571000.0,720,308,5180,5202.799359,0.187962,27680
2,3.0,0.000574,10.7040,1425.0,2.0877,20256000.0,831,561,8700,8744.728298,0.251285,34800
3,4.0,0.023758,11.2370,1425.0,2.5802,5203100.0,140,83,1197,1198.461260,0.228365,5248
4,5.0,0.013448,19.0300,1500.0,2.2267,69126000.0,656,2365,2262,2293.460987,0.088946,25785
5,6.0,0.036538,12.0600,1425.0,2.4961,20902000.0,440,494,1125,1152.568218,0.053459,21560
6,7.0,0.017869,37.1500,1350.0,2.1056,27810000.0,1,439,2149,2157.415818,0.153422,14062
7,8.0,0.021748,6.9778,1650.0,2.0095,5220000.0,159,129,4563,4571.162963,0.191262,23900
8,10.0,0.004804,15.4040,1575.0,1.5889,57802000.0,1191,1902,2538,2608.949895,0.054954,47475
9,11.0,0.005442,13.0990,1650.0,2.9142,32676000.0,608,1057,534,548.967041,0.054246,10120
10,12.0,0.041692,15.0480,1425.0,2.0142,95816000.0,2394,2320,2772,2829.498026,0.058985,47970
11,13.0,0.017000,7.6422,1650.0,2.9322,15452000.0,515,309,344,348.482799,0.070315,4956
12,14.0,0.018148,40.5890,1425.0,1.7481,52751000.0,33,1653,1198,1212.895733,0.031901,38021
13,15.0,0.026241,19.1890,1500.0,3.2359,4303100.0,44,31,4541,4553.360756,0.299682,15194
14,16.0,0.028223,29.4540,1725.0,2.3301,81242000.0,1815,1330,5243,5258.690654,0.193733,27144
15,17.0,0.009446,30.5390,1575.0,2.4613,61779000.0,185,1537,1528,1534.969684,0.089581,17135
16,18.0,0.020719,6.3567,1425.0,2.2444,10912000.0,270,43,258,262.213506,0.069701,3762
17,19.0,0.008119,2.4609,1725.0,2.6646,42446000.0,4766,251,1569,1626.572288,0.107054,15194
18,20.0,0.015030,11.7430,1575.0,2.6242,36844000.0,886,1043,20338,20366.408393,0.421168,48357
19,21.0,0.033795,45.2920,1350.0,2.4379,38571000.0,0,931,358,368.753608,0.023108,15958
20,22.0,0.009653,32.2290,1500.0,2.1629,67568000.0,215,2266,635,645.083106,0.027446,23504
21,23.0,0.073487,13.1200,1575.0,1.5577,3273800.0,16,15,600,602.444307,0.050711,11880
22,24.0,0.038199,5.6431,2700.0,4.0400,3735000.0,102,23,1389,1390.444782,0.202453,6868
23,25.0,0.022180,48.5710,1350.0,1.8653,59490000.0,92,2059,6881,6904.806177,0.151995,45428
24,27.0,0.014051,16.6780,1725.0,2.7998,74036000.0,1984,3286,4447,4497.453387,0.089198,50421
25,28.0,0.014850,11.1860,1725.0,2.8374,22202000.0,1003,448,634,642.822616,0.066435,9676
26,29.0,0.005388,3.0773,1650.0,2.1762,52942000.0,5638,395,2781,2888.103639,0.148412,19460
27,30.0,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816

In [44]:
input_data_11 = pd.merge(H_data, geomorph_cvhv_sat, on=["Site"])
del input_data_11["Chronicle"]
input_data_11.to_csv("data/Input_Data_Complete_Rates_30_Features_Geomorph_CVHV_Saturation_BVE.csv", sep=";", index=None)
input_data_11

,Site,Rate,H Error,Slope,Elevation,LC,CW,Area,Coastal Vulnerability,Hydrological Vulnerability,Satured Zone Area,Vulnerability Sum,Vulnerability Rate,Global Area of site (in cells)
0,1.0,1.0,0.000000,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
1,1.0,2.0,0.003879,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
2,1.0,7.0,0.016209,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
3,1.0,15.0,0.025983,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
4,1.0,21.0,0.031977,0.017383,14.0310,1575.0,2.2527,57077000.0,1906,1033,10373,10398.720357,0.296041,35126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,30.0,2000.0,0.142734,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
746,30.0,2250.0,0.150898,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
747,30.0,3000.0,0.161572,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
748,30.0,3182.0,0.165746,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816
749,30.0,3652.0,0.168162,0.009400,7.9139,1800.0,2.0684,46513000.0,841,1156,19157,19204.851462,0.393413,48816

In [92]:
    if rate == 1:
        folder = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0"
        file_name_BV = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_errorsresult_H_BVE.csv"
        
    else:
        folder = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Approx0_Period" + str(float(rate))
        file_name_BV = "model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_Approx0_Period" + str(float(rate)) + "_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site" + str(site_number) + "_Chronicle0_errorsresult_H_BVE.csv"

    file_name_time = folder + ".list"

Empty DataFrame
Columns: [Site, Chronicle, Rate, H Error]
Index: []

In [52]:
print("model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_errorsresult_H_BVE.csv")

model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_errorsresult_H_BVE.csv

In [47]:
data.loc[len(data.index)] = [site_number, 0, rate, h_error]

In [48]:
print(data)

   Site  Chronicle  Rate   H Error
0   1.0        0.0   2.0  0.003879

In [ ]:
                                                                                                                        
result_file = folder_results_path + "/" + site_name + "/" + file_name_BV                                                                                                                              
                                                                                                                              
try:
    df = pd.read_csv(result_file, sep=";")
except:
    print("result_file: ", result_file)
    print("File for site " + site_name + " (number : " + str(site_number) + " & chronicle 0"  + ") does not exist")
    df = pd.DataFrame()
# + str(chronicle)

In [24]:
print("model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_Approx0_Period2.0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_errorsresult_H_BVE")

model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_Approx0_Period2.0_Ref_model_time_0_geo_0_thick_1_K_27.32_Sy_0.1_Step1_site1_Chronicle0_errorsresult_H_BVE